In [1]:
import numpy as np
import rasterio

In [2]:
filename = "example.tif"

In [3]:
dataset = rasterio.open(filename)

In [4]:
print(f'Raster Dimensions: {dataset.width}x{dataset.height}')

Raster Dimensions: 6232x3064


In [5]:
print(f'Bounding Box: {dataset.bounds}')

Bounding Box: BoundingBox(left=-83.29979735053544, bottom=34.97044502421424, right=-83.29651657390043, top=34.97205803763043)


In [6]:
print(f'Coordinate Reference System (crs): {dataset.crs}')

Coordinate Reference System (crs): GEOGCS["WGS 84",DATUM["World Geodetic System 1984",SPHEROID["WGS 84",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST]]


In [7]:
print(f'Affine transformation matrix: {dataset.transform}')

Affine transformation matrix: | 0.00, 0.00,-83.30|
| 0.00,-0.00, 34.97|
| 0.00, 0.00, 1.00|


In [8]:
elevation = dataset.read(1)
print(f'Elevation data (first 10x10 pixels):\n{elevation[:10,:10]}')

Elevation data (first 10x10 pixels):
[[-9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999.]
 [-9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999.]
 [-9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999.]
 [-9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999.]
 [-9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999.]
 [-9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999.]
 [-9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999.]
 [-9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999.]
 [-9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999.]
 [-9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999. -9999.]]


In [9]:
print(f'Elevation data: {elevation[0,0]}')

Elevation data: -9999.0


In [12]:
print(f'Pixel Size: ({dataset.transform[0], dataset.transform[4]})')

Pixel Size: ((5.264404099830666e-07, -5.264404099830666e-07))
